---
title: "database"
author: "xiaofan xia"
date: "10/29/2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(RSQLite)
library(DBI)
```


Elimanate duplicative columns from the same table. 

```{r warning=FALSE}
donor <- read.csv("Top MA Donors 2016-2020(1).csv")
donor_new <- donor[1:19]
donor_new <- unique(donor_new)
```

The primary keys I chose is fectransid (A unique record identifier within a given cycle.)
```{r warning=FALSE}
contrib <- donor_new[c(2:12,17:18)]
contrib %>% distinct()

recip <- donor_new[c(12:16,18:19)]
recip %>% distinct()

demographic_contrib <- 
  donor_new %>%
  select(contribid,City,State,Zip,fectransid)
demographic_contrib %>% distinct()

political_contrib <- 
  donor_new %>%
  select(contribid,cycle,fam,Fecoccemp,orgname,ultorg,party,fectransid)
political_contrib %>% distinct()

contributions <-  
  donor_new %>% 
  select(contribid,date,amount,recipid,fectransid)
contributions %>% distinct()
```

Generate Sqlite database.
```{r}
ma_donor<- dbConnect(SQLite(),"XiaofanXia.sqlite")
dbWriteTable(ma_donor,"contributor",contrib)

dbWriteTable(ma_donor,"recipients",recip)
dbWriteTable(ma_donor,"demographic_contributors",demographic_contrib)
dbWriteTable(ma_donor,"political_ontributors",political_contrib)
dbWriteTable(ma_donor,"contributions",contributions)

```